-- Valori anagrafici ripetuti, salvati una sola volta.
CREATE TABLE tipologie_stakeholder (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE regioni (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE canali_ingaggio (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE partecipanti (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_excel BIGINT NOT NULL UNIQUE,
    nome_cognome VARCHAR(255) NOT NULL,
    email VARCHAR(320) NOT NULL UNIQUE,
    tipologia_stakeholder_id BIGINT NOT NULL,
    regione_id BIGINT NOT NULL,
    canale_ingaggio_id BIGINT NOT NULL,
    in_database_dem BOOLEAN NOT NULL,
    creato_il TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    aggiornato_il TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_partecipante_tipologia
        FOREIGN KEY (tipologia_stakeholder_id) REFERENCES tipologie_stakeholder(id),
    CONSTRAINT fk_partecipante_regione
        FOREIGN KEY (regione_id) REFERENCES regioni(id),
    CONSTRAINT fk_partecipante_canale
        FOREIGN KEY (canale_ingaggio_id) REFERENCES canali_ingaggio(id)
);

CREATE INDEX idx_partecipanti_tipologia ON partecipanti(tipologia_stakeholder_id);
CREATE INDEX idx_partecipanti_regione ON partecipanti(regione_id);
CREATE INDEX idx_partecipanti_canale ON partecipanti(canale_ingaggio_id);

-- I 17 touchpoint sono divisi per argomento invece di allargare partecipanti.
CREATE TABLE interazioni_email (
    partecipante_id BIGINT PRIMARY KEY,
    dem_inviata BOOLEAN NOT NULL,
    dem_consegnata BOOLEAN NOT NULL,
    dem_aperta BOOLEAN NOT NULL,
    CONSTRAINT fk_email_partecipante
        FOREIGN KEY (partecipante_id) REFERENCES partecipanti(id) ON DELETE CASCADE
);

CREATE TABLE interazioni_linkedin (
    partecipante_id BIGINT PRIMARY KEY,
    annuncio_reach BOOLEAN NOT NULL,
    annuncio_interazione BOOLEAN NOT NULL,
    recap_reach BOOLEAN NOT NULL,
    recap_interazione BOOLEAN NOT NULL,
    CONSTRAINT fk_linkedin_partecipante
        FOREIGN KEY (partecipante_id) REFERENCES partecipanti(id) ON DELETE CASCADE
);

CREATE TABLE interazioni_stand (
    partecipante_id BIGINT PRIMARY KEY,
    visita_stand BOOLEAN NOT NULL,
    giorno_visita DATE,
    visualizzazioni INTEGER NOT NULL CHECK (visualizzazioni >= 0),
    scroll INTEGER NOT NULL CHECK (scroll >= 0),
    CONSTRAINT fk_stand_partecipante
        FOREIGN KEY (partecipante_id) REFERENCES partecipanti(id) ON DELETE CASCADE
);

CREATE TABLE interazioni_sala_vip (
    partecipante_id BIGINT PRIMARY KEY,
    accesso_sala_vip BOOLEAN NOT NULL,
    risposte_wordcloud INTEGER NOT NULL CHECK (risposte_wordcloud >= 0),
    CONSTRAINT fk_sala_vip_partecipante
        FOREIGN KEY (partecipante_id) REFERENCES partecipanti(id) ON DELETE CASCADE
);

CREATE TABLE interazioni_simposio (
    partecipante_id BIGINT PRIMARY KEY,
    presenza_simposio BOOLEAN NOT NULL,
    permanenza_min INTEGER CHECK (permanenza_min BETWEEN 0 AND 59),
    focus_rate DECIMAL(5, 4) CHECK (focus_rate BETWEEN 0 AND 1),
    quiz_completati INTEGER NOT NULL CHECK (quiz_completati >= 0),
    CONSTRAINT fk_simposio_partecipante
        FOREIGN KEY (partecipante_id) REFERENCES partecipanti(id) ON DELETE CASCADE
);
